import React, { useState } from 'react';
import type { ClientPortalClient, ClientPortalProject, ClientPortalTask, ClientPortalInvoice, ClientPortalMeeting, ClientPortalDocument } from '../api-client-portal';

interface P {
  clients: ClientPortalClient[]; projects: ClientPortalProject[]; tasks: ClientPortalTask[]; invoices: ClientPortalInvoice[];
  meetings: ClientPortalMeeting[]; documents: ClientPortalDocument[];
  onAddClient: any; onUpdateClient: any; onDeleteClient: any;
  onAddProject: any; onUpdateProject: any; onDeleteProject: any;
  onAddTask: any; onUpdateTask: any; onDeleteTask: any;
  onAddInvoice: any; onUpdateInvoice: any; onDeleteInvoice: any;
  onAddMeeting: any; onUpdateMeeting: any; onDeleteMeeting: any;
  onAddDocument: any; onUpdateDocument: any; onDeleteDocument: any;
}

const SC: Record<string,string> = { lead:'badge-clay', contracted:'badge-camel', onboarding:'badge-info', active:'badge-success', paused:'badge-warning', complete:'badge-info', offboarded:'badge-muted' };
const HC: Record<string,string> = { green:'#34764d', yellow:'#a66b00', red:'#a83832' };

export function ClientMgmtView(props:P) {
  const [sid, setSid] = useState<string|null>(null);
  const [tab, setTab] = useState('overview');
  const [modal, setModal] = useState('');
  const c = props.clients.find(x=>x.id===sid);
  const ps = props.projects.filter(x=>x.clientId===sid);
  const ts = props.tasks.filter(t=>ps.some(p=>p.id===t.projectId));
  const inv = props.invoices.filter(x=>x.clientId===sid);
  const ms = props.meetings.filter(m=>ps.some(p=>p.id===m.projectId));
  const ds = props.documents.filter(d=>ps.some(p=>p.id===d.projectId));
  const bal = inv.reduce((s,i)=>s+(i.amount-i.amountPaid),0);
  const prog = ps.length?Math.round(ps.reduce((s,p)=>s+p.progress,0)/ps.length):0;
  const [f, setF] = useState({name:'',email:'',company:'',status:'lead',portalAccess:false});
  const [pf, setPF] = useState({name:'',description:'',status:'planning',progress:0,startDate:'',targetDate:'',health:'green' as const});
  const [tf, setTF] = useState({title:'',status:'backlog',dueDate:'',assignee:''});
  const [nf, setNF] = useState({amount:0,amountPaid:0,status:'draft',dueDate:''});
  const [mf, setMF] = useState({title:'',date:'',notes:'',status:'scheduled'});
  const [df, setDF] = useState({title:'',url:'',status:'draft'});

  const addC = ()=>{ if(!f.name||!f.email)return; props.onAddClient({...f, accessToken:Math.random().toString(36).slice(2,10), portalAccess:true}); setF({name:'',email:'',company:'',status:'lead',portalAccess:false}); setModal(''); };
  const addP = ()=>{ if(!sid||!pf.name)return; props.onAddProject({...pf,clientId:sid}); setPF({name:'',description:'',status:'planning',progress:0,startDate:'',targetDate:'',health:'green'}); setModal(''); };
  const addT = ()=>{ if(!sid||!ps.length||!tf.title)return; props.onAddTask({...tf,projectId:ps[0].id}); setTF({title:'',status:'backlog',dueDate:'',assignee:''}); setModal(''); };
  const addI = ()=>{ if(!sid)return; props.onAddInvoice({...nf,clientId:sid}); setNF({amount:0,amountPaid:0,status:'draft',dueDate:''}); setModal(''); };
  const addM = ()=>{ if(!sid||!ps.length||!mf.title)return; props.onAddMeeting({...mf,projectId:ps[0].id}); setMF({title:'',date:'',notes:'',status:'scheduled'}); setModal(''); };
  const addD = ()=>{ if(!sid||!ps.length||!df.title)return; props.onAddDocument({...df,projectId:ps[0].id}); setDF({title:'',url:'',status:'draft'}); setModal(''); };

  return (<div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}>
      <h1 style={{color:'var(--ths-ink,#17233a)'}}>Projects</h1>
      <button className='btn-primary' onClick={()=>setModal('client')} style={{background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'8px 14px',fontWeight:600,cursor:'pointer'}}>+ Client</button>
    </div>
    <div className='card' style={{marginBottom:20,background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10}}>
      <div style={{display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}>
        <select value={sid||''} onChange={e=>{setSid(e.target.value||null);setTab('overview');}} style={{minWidth:220,padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)'}}>
          <option value=''>Select a client...</option>
          {props.clients.map(c=>(<option key={c.id} value={c.id}>{c.name} ({c.company||c.email})</option>))}
        </select>
        {c&&(<><span className={'badge '+(SC[c.status]||'badge-info')} style={{padding:'4px 10px',borderRadius:20,fontSize:'0.8rem',fontWeight:600}}>{c.status}</span>{c.portalAccess&&<span className='badge badge-success' style={{padding:'4px 10px',borderRadius:20,fontSize:'0.8rem',fontWeight:600,background:'#34764d',color:'white'}}>Portal active</span>}</>)}
      </div>
    </div>
    {c&&(<><div style={{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap'}}>
      {['overview','projects','tasks','invoices','meetings','documents'].map(t=>(
        <button key={t} className={'btn-tab '+(tab===t?'active':'')} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>
      ))}
    </div>
    {tab==='overview'&&(<div className='view-grid'>
      <div className='card' style={{borderTop:'4px solid var(--ths-blue,#244b7a)',background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)',marginBottom:4}}>Projects</div><div style={{fontSize:'1.5rem',fontWeight:700,color:'var(--ths-ink,#17233a)'}}>{ps.length}</div></div>
      <div className='card' style={{borderTop:'4px solid var(--ths-gold,#d59b3b)',background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)',marginBottom:4}}>Avg Progress</div><div style={{fontSize:'1.5rem',fontWeight:700,color:'var(--ths-ink,#17233a)'}}>{prog}%</div></div>
      <div className='card' style={{borderTop:'4px solid var(--ths-ink,#17233a)',background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)',marginBottom:4}}>Total Invoiced</div><div style={{fontSize:'1.5rem',fontWeight:700,color:'var(--ths-ink,#17233a)'}}>${inv.reduce((s,i)=>s+i.amount,0).toLocaleString()}</div></div>
      <div className='card' style={{borderTop:'4px solid var(--ths-sage,#34764d)',background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)',marginBottom:4}}>Balance Due</div><div style={{fontSize:'1.5rem',fontWeight:700',color:bal>0?'var(--ths-red,#a83832)':'var(--ths-ink,#17233a)'}}>${bal.toLocaleString()}</div></div>
      <div className='card' style={{borderTop:'4px solid var(--ths-yellow,#a66b00)',background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)',marginBottom:4}}>Open Tasks</div><div style={{fontSize:'1.5rem',fontWeight:700,color:'var(--ths-ink,#17233a)'}}>{ts.filter(t=>t.status!=='done').length}</div></div>
      <div className='card' style={{borderTop:'4px solid var(--ths-line,#ccd5e1)',background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)',marginBottom:4}}>Access Token</div><div style={{fontSize:'0.9rem',fontFamily:'monospace',wordBreak:'break-all',color:'var(--ths-ink,#17233a)'}}>{c.accessToken||'-'}</div></div>
    </div>)}
    {tab==='projects'&&(<><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><h3 style={{color:'var(--ths-ink,#17233a)'}}>Projects</h3><button className='btn-primary' onClick={()=>setModal('project')} style={{background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'6px 12px',fontWeight:600,cursor:'pointer'}}>+ Project</button></div><div className='view-grid'>
      {ps.map(p=>(<div key={p.id} className='card' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><h4 style={{marginBottom:4,color:'var(--ths-ink,#17233a)'}}>{p.name}</h4><span className='badge badge-info' style={{padding:'4px 10px',borderRadius:20,fontSize:'0.8rem',fontWeight:600,background:'var(--ths-light,#e8f0f8)',color:'var(--ths-blue,#244b7a)'}}>{p.status}</span></div>
      {p.description&&<p style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>{p.description}</p>}
      <div style={{marginTop:8}}><div style={{height:6,background:'var(--ths-line,#ccd5e1)',borderRadius:3,overflow:'hidden'}}><div style={{width:p.progress+'%',height:'100%',background:HC[p.health||'green'],borderRadius:3}}/></div><div style={{display:'flex',justifyContent:'space-between',fontSize:'0.8rem',marginTop:4,color:'var(--ths-muted,#667085)'}}><span>{p.progress}%</span>{p.targetDate&&<span>Due {new Date(p.targetDate).toLocaleDateString()}</span>}</div></div>
      <div style={{display:'flex',gap:6,marginTop:10}}><button className='btn-sm' onClick={()=>{const n=['green','yellow','red'];const i=n.indexOf(p.health||'green');props.onUpdateProject(p.id,{health:n[(i+1)%3] as any});}}>Health: {p.health||'green'}</button><button className='btn-sm' onClick={()=>props.onDeleteProject(p.id)}>Delete</button></div></div>))}
    </div></>)}
    {tab==='tasks'&&(<><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><h3 style={{color:'var(--ths-ink,#17233a)'}}>Tasks</h3><button className='btn-primary' onClick={()=>setModal('task')} style={{background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'6px 12px',fontWeight:600,cursor:'pointer'}}>+ Task</button></div><div className='card' style={{overflowX:'auto',background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><table className='cr8w-table'><thead><tr><th>Task</th><th>Status</th><th>Due</th><th>Owner</th><th /></tr></thead><tbody>
      {ts.map(t=>(<tr key={t.id}><td style={{color:'var(--ths-ink,#17233a)'}}>{t.title}</td><td><span className={'badge badge-'+ (t.status==='done'?'success':t.status==='in-progress'?'info':'clay')} style={{padding:'4px 10px',borderRadius:20,fontSize:'0.75rem',fontWeight:600}}>{t.status}</span></td><td style={{color:'var(--ths-muted,#667085)'}}>{t.dueDate?new Date(t.dueDate).toLocaleDateString():'-'}</td><td style={{color:'var(--ths-muted,#667085)'}}>{t.assignee||'-'}</td><td><button className='btn-sm' onClick={()=>props.onDeleteTask(t.id)}>Delete</button></td></tr>))}
    </tbody></table></div></>)}
    {tab==='invoices'&&(<><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><h3 style={{color:'var(--ths-ink,#17233a)'}}>Invoices</h3><button className='btn-primary' onClick={()=>setModal('invoice')} style={{background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'6px 12px',fontWeight:600,cursor:'pointer'}}>+ Invoice</button></div><div className='card' style={{overflowX:'auto',background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><table className='cr8w-table'><thead><tr><th>Amount</th><th>Paid</th><th>Balance</th><th>Status</th><th>Due</th><th /></tr></thead><tbody>
      {inv.map(i=>(<tr key={i.id}><td style={{color:'var(--ths-ink,#17233a)'}}>${i.amount.toLocaleString()}</td><td style={{color:'var(--ths-ink,#17233a)'}}>${i.amountPaid.toLocaleString()}</td><td style={{color:(i.amount-i.amountPaid)>0?'var(--ths-red,#a83832)':'var(--ths-ink,#17233a)'}}>${(i.amount-i.amountPaid).toLocaleString()}</td><td><span className={'badge badge-'+(i.status==='paid'?'success':i.status==='overdue'?'danger':'info')} style={{padding:'4px 10px',borderRadius:20,fontSize:'0.75rem',fontWeight:600}}>{i.status}</span></td><td style={{color:'var(--ths-muted,#667085)'}}>{i.dueDate?new Date(i.dueDate).toLocaleDateString():'-'}</td><td><button className='btn-sm' onClick={()=>props.onDeleteInvoice(i.id)}>Delete</button></td></tr>))}
    </tbody></table></div></>)}
    {tab==='meetings'&&(<><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><h3 style={{color:'var(--ths-ink,#17233a)'}}>Meetings</h3><button className='btn-primary' onClick={()=>setModal('meeting')} style={{background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'6px 12px',fontWeight:600,cursor:'pointer'}}>+ Meeting</button></div><div className='view-grid'>
      {ms.map(m=>(<div key={m.id} className='card' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><h4 style={{color:'var(--ths-ink,#17233a)'}}>{m.title}</h4><span className={'badge badge-'+(m.status==='completed'?'success':'info')} style={{padding:'4px 10px',borderRadius:20,fontSize:'0.8rem',fontWeight:600}}>{m.status}</span></div><div style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)',marginTop:4}}>{new Date(m.date).toLocaleString()}</div>{m.notes&&<p style={{fontSize:'0.85rem',marginTop:8,color:'var(--ths-ink,#17233a)'}}>{m.notes}</p>}</div>))}
    </div></>)}
    {tab==='documents'&&(<><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><h3 style={{color:'var(--ths-ink,#17233a)'}}>Documents</h3><button className='btn-primary' onClick={()=>setModal('document')} style={{background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'6px 12px',fontWeight:600,cursor:'pointer'}}>+ Document</button></div><div className='view-grid'>
      {ds.map(d=>(<div key={d.id} className='card' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:10,padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><h4 style={{color:'var(--ths-ink,#17233a)'}}>{d.title}</h4><span className={'badge badge-'+(d.status==='approved'?'success':d.status==='shared'?'info':'clay')} style={{padding:'4px 10px',borderRadius:20,fontSize:'0.8rem',fontWeight:600}}>{d.status}</span></div>{d.url&&<a href={d.url} target='_blank' rel='noreferrer' style={{fontSize:'0.85rem',color:'var(--ths-blue,#244b7a)'}}>Open →</a>}</div>))}
    </div></>)}
    </>)}
    {modal==='client'&&(<div className='modal-overlay' onClick={e=>{if(e.target===e.currentTarget)setModal('');}}><div className='modal-content' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:12,padding:24,maxWidth:420}}><div className='modal-header' style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><span className='modal-title' style={{fontWeight:700,color:'var(--ths-ink,#17233a)'}}>New Client</span><button className='modal-close' onClick={()=>setModal('')} style={{background:'none',border:'none',fontSize:'1.2rem',cursor:'pointer',color:'var(--ths-muted,#667085)'}}>×</button></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Name</label><input value={f.name} onChange={e=>setF({...f,name:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Email</label><input type='email' value={f.email} onChange={e=>setF({...f,email:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Company</label><input value={f.company} onChange={e=>setF({...f,company:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <div className='form-row' style={{display:'flex',gap:12}}><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Status</label><select value={f.status} onChange={e=>setF({...f,status:e.target.value as any})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}><option value='lead'>Lead</option><option value='contracted'>Contracted</option><option value='onboarding'>Onboarding</option><option value='active'>Active</option><option value='paused'>Paused</option><option value='complete'>Complete</option><option value='offboarded'>Offboarded</option></select></div><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Portal Access</label><select value={String(f.portalAccess)} onChange={e=>setF({...f,portalAccess:e.target.value==='true'})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}><option value='true'>Enabled</option><option value='false'>Disabled</option></select></div></div>
      <button className='btn-primary' style={{width:'100%',background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'10px 0',fontWeight:600,cursor:'pointer'}} onClick={addC}>Create Client</button>
    </div></div>)}
    {modal==='project'&&(<div className='modal-overlay' onClick={e=>{if(e.target===e.currentTarget)setModal('');}}><div className='modal-content' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:12,padding:24,maxWidth:420}}><div className='modal-header' style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><span className='modal-title' style={{fontWeight:700,color:'var(--ths-ink,#17233a)'}}>New Project</span><button className='modal-close' onClick={()=>setModal('')} style={{background:'none',border:'none',fontSize:'1.2rem',cursor:'pointer',color:'var(--ths-muted,#667085)'}}>×</button></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Name</label><input value={pf.name} onChange={e=>setPF({...pf,name:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Description</label><textarea value={pf.description} onChange={e=>setPF({...pf,description:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4,minHeight:60}}/></div>
      <div className='form-row' style={{display:'flex',gap:12}}><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Status</label><select value={pf.status} onChange={e=>setPF({...pf,status:e.target.value as any})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}><option value='planning'>Planning</option><option value='in-progress'>In Progress</option><option value='review'>Review</option><option value='delivered'>Delivered</option><option value='paused'>Paused</option></select></div><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Health</label><select value={pf.health} onChange={e=>setPF({...pf,health:e.target.value as any})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}><option value='green'>Green</option><option value='yellow'>Yellow</option><option value='red'>Red</option></select></div></div>
      <div className='form-row' style={{display:'flex',gap:12}}><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Progress %</label><input type='number' min={0} max={100} value={pf.progress} onChange={e=>setPF({...pf,progress:Number(e.target.value)})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Start</label><input type='date' value={pf.startDate} onChange={e=>setPF({...pf,startDate:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Target</label><input type='date' value={pf.targetDate} onChange={e=>setPF({...pf,targetDate:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div></div>
      <button className='btn-primary' style={{width:'100%',background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'10px 0',fontWeight:600,cursor:'pointer'}} onClick={addP}>Create Project</button>
    </div></div>)}
    {modal==='task'&&(<div className='modal-overlay' onClick={e=>{if(e.target===e.currentTarget)setModal('');}}><div className='modal-content' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:12,padding:24,maxWidth:420}}><div className='modal-header' style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><span className='modal-title' style={{fontWeight:700,color:'var(--ths-ink,#17233a)'}}>New Task</span><button className='modal-close' onClick={()=>setModal('')} style={{background:'none',border:'none',fontSize:'1.2rem',cursor:'pointer',color:'var(--ths-muted,#667085)'}}>×</button></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Title</label><input value={tf.title} onChange={e=>setTF({...tf,title:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <div className='form-row' style={{display:'flex',gap:12}}><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Status</label><select value={tf.status} onChange={e=>setTF({...tf,status:e.target.value as any})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}><option value='backlog'>Backlog</option><option value='todo'>To Do</option><option value='in-progress'>In Progress</option><option value='in-review'>In Review</option><option value='done'>Done</option></select></div><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Due</label><input type='date' value={tf.dueDate} onChange={e=>setTF({...tf,dueDate:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Assignee</label><input value={tf.assignee} onChange={e=>setTF({...tf,assignee:e.target.value})} placeholder='sunshine, monny, ...' style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <button className='btn-primary' style={{width:'100%',background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'10px 0',fontWeight:600,cursor:'pointer'}} onClick={addT}>Create Task</button>
    </div></div>)}
    {modal==='invoice'&&(<div className='modal-overlay' onClick={e=>{if(e.target===e.currentTarget)setModal('');}}><div className='modal-content' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:12,padding:24,maxWidth:420}}><div className='modal-header' style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><span className='modal-title' style={{fontWeight:700,color:'var(--ths-ink,#17233a)'}}>New Invoice</span><button className='modal-close' onClick={()=>setModal('')} style={{background:'none',border:'none',fontSize:'1.2rem',cursor:'pointer',color:'var(--ths-muted,#667085)'}}>×</button></div>
      <div className='form-row' style={{display:'flex',gap:12}}><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Amount</label><input type='number' value={nf.amount} onChange={e=>setNF({...nf,amount:Number(e.target.value)})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Paid</label><input type='number' value={nf.amountPaid} onChange={e=>setNF({...nf,amountPaid:Number(e.target.value)})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div></div>
      <div className='form-row' style={{display:'flex',gap:12}}><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Status</label><select value={nf.status} onChange={e=>setNF({...nf,status:e.target.value as any})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}><option value='draft'>Draft</option><option value='sent'>Sent</option><option value='paid'>Paid</option><option value='overdue'>Overdue</option><option value='cancelled'>Cancelled</option></select></div><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Due Date</label><input type='date' value={nf.dueDate} onChange={e=>setNF({...nf,dueDate:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div></div>
      <button className='btn-primary' style={{width:'100%',background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'10px 0',fontWeight:600,cursor:'pointer'}} onClick={addI}>Create Invoice</button>
    </div></div>)}
    {modal==='meeting'&&(<div className='modal-overlay' onClick={e=>{if(e.target===e.currentTarget)setModal('');}}><div className='modal-content' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:12,padding:24,maxWidth:420}}><div className='modal-header' style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><span className='modal-title' style={{fontWeight:700,color:'var(--ths-ink,#17233a)'}}>New Meeting</span><button className='modal-close' onClick={()=>setModal('')} style={{background:'none',border:'none',fontSize:'1.2rem',cursor:'pointer',color:'var(--ths-muted,#667085)'}}>×</button></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Title</label><input value={mf.title} onChange={e=>setMF({...mf,title:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <div className='form-row' style={{display:'flex',gap:12}}><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Date & Time</label><input type='datetime-local' value={mf.date} onChange={e=>setMF({...mf,date:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div><div className='form-group' style={{flex:1,marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Status</label><select value={mf.status} onChange={e=>setMF({...mf,status:e.target.value as any})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}><option value='scheduled'>Scheduled</option><option value='completed'>Completed</option><option value='cancelled'>Cancelled</option></select></div></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Notes</label><textarea value={mf.notes} onChange={e=>setMF({...mf,notes:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4,minHeight:60}}/></div>
      <button className='btn-primary' style={{width:'100%',background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'10px 0',fontWeight:600,cursor:'pointer'}} onClick={addM}>Create Meeting</button>
    </div></div>)}
    {modal==='document'&&(<div className='modal-overlay' onClick={e=>{if(e.target===e.currentTarget)setModal('');}}><div className='modal-content' style={{background:'var(--ths-paper,#fff)',border:'1px solid var(--ths-line,#ccd5e1)',borderRadius:12,padding:24,maxWidth:420}}><div className='modal-header' style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><span className='modal-title' style={{fontWeight:700,color:'var(--ths-ink,#17233a)'}}>New Document</span><button className='modal-close' onClick={()=>setModal('')} style={{background:'none',border:'none',fontSize:'1.2rem',cursor:'pointer',color:'var(--ths-muted,#667085)'}}>×</button></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Title</label><input value={df.title} onChange={e=>setDF({...df,title:e.target.value})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>URL</label><input value={df.url} onChange={e=>setDF({...df,url:e.target.value})} placeholder='https://...' style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}/></div>
      <div className='form-group' style={{marginBottom:12}}><label style={{fontSize:'0.85rem',color:'var(--ths-muted,#667085)'}}>Status</label><select value={df.status} onChange={e=>setDF({...df,status:e.target.value as any})} style={{width:'100%',padding:8,borderRadius:7,border:'1px solid var(--ths-line,#ccd5e1)',marginTop:4}}><option value='draft'>Draft</option><option value='shared'>Shared</option><option value='approved'>Approved</option><option value='rejected'>Rejected</option></select></div>
      <button className='btn-primary' style={{width:'100%',background:'var(--ths-blue,#244b7a)',color:'white',border:'none',borderRadius:7,padding:'10px 0',fontWeight:600,cursor:'pointer'}} onClick={addD}>Create Document</button>
    </div></div>)}
  </div>);
}
