// CR8W Supabase configuration — NOT autogenerated.
// This file is safe to edit. Figma Make only touches utils/supabase/info.tsx.

export const projectId = 'axntibrdivccycxdwlzk'
export const supabaseUrl = 'https://axntibrdivccycxdwlzk.supabase.co'
export const jwksUrl = 'https://axntibrdivccycxdwlzk.supabase.co/auth/v1/.well-known/jwks.json'

// Publishable key — safe for client-side (not a secret)
export const publishableKey = 'sb_publishable_KKMWtvpxkSGaq-xmie6viQ_pRzAb_4i'

// Legacy anon key (fallback only)
export const publicAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4bnRpYnJkaXZjY3ljeGR3bHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMxMTIxNTYsImV4cCI6MjA5ODY4ODE1Nn0.CFAeOeCwyOrOAfi4UecF7IlfUmUQw2pmEB20S80FUMc'
