// Safe source of truth — NOT autogenerated by Figma Make
// Edit this file freely. Keep info.tsx untouched.
export const supabaseUrl = 'https://axntibrdivccycxdwlzk.supabase.co';
export const publishableKey = 'sb_publishable_KKMWtvpxkSGaq-xmie6viQ_pRzAb_4i';
export const publicAnonKey = 'sb_publishable_KKMWtvpxkSGaq-xmie6viQ_pRzAb_4i';
export const jwksUrl = 'https://axntibrdivccycxdwlzk.supabase.co/auth/v1/.well-known/jwks.json';
